apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: %eks_node_instance_role_arn%
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::065357747629:user/steinn
      username: admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::065357747629:user/borgar
      username: admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::065357747629:user/autodeploy
      username: admin
      groups:
        - system:masters
