apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: %eks_node_instance_role_arn%
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
# Here you can add several IAM user mappings so you (and your coworkers,
# or bots) can access the kubernetes API. examples:
#  mapUsers: |
#    - userarn: arn:aws:iam::123456:user/steinn
#      username: admin
#      groups:
#        - system:masters
#    - userarn: arn:aws:iam::123456:user/autodeploy
#      username: admin
#      groups:
#        - system:masters
