kind: Service
apiVersion: v1
metadata:
  name: traefik-proxy
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.grid.is
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:065357747629:certificate/a1ce7bf3-a4c8-495a-ae5c-4bae5993b6f9"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: traefik-proxy
    tier: proxy
  ports:
  - port: 443
    targetPort: 80
