apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy-nlb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik-nlb.grid.is
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:065357747629:certificate/a1ce7bf3-a4c8-495a-ae5c-4bae5993b6f9"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-nlb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 443
      targetPort: 8881
      name: terminated-tls