---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-nlb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-nlb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-nlb
        name: traefik-ingress-nlb
    spec:
      volumes:
        - name: config
          configMap:
            name: traefik-conf
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-nlb
        volumeMounts:
          - mountPath: "/config"
            name: "config"
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        - name: terminated-tls
          containerPort: 8881
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
        - --kubernetes.ingressendpoint.publishedservice=default/traefik-proxy-nlb
